import React from "react";

export const Services = () => {
  return (
    <div className="w-full min-h-screen relative bg-white px-4 md:px-16 py-10">
      {/* Header Image */}
      <div className="w-full relative">
        {/* Desktop Version */}
        <div className="hidden md:block relative w-full h-[300px] overflow-hidden">
         
          <div className="absolute top-[10%] left-0 w-full h-full flex flex-col items-center justify-center text-center px-4">
            <h1 className="text-[#8dc442] text-3xl md:text-[36px] font-bold mb-2">
              Terms Of Services
            </h1>
            <p className="text-[#3f5224] text-base md:text-[24px] mt-4 tracking-wide font-semibold">
              Read all terms and conditions.
            </p>
          </div>
        </div>

        {/* Mobile Version */}
        <div className="block md:hidden relative w-full h-[300px] overflow-hidden">
      
          <div className="absolute top-[12%] left-0 w-full h-full flex flex-col items-center justify-center text-center px-4">
            <h1 className="text-[#8dc442] text-3xl font-bold mb-2">
              Terms Of Services
            </h1>
            <p className="text-[#3f5224] text-lg mt-3 font-semibold">
              Read all terms and conditions.
            </p>
          </div>
        </div>
      </div>

      {/* Terms Content */}
      <div className="mt-10 space-y-6 text-[#3f5224]">
        <h2 className="text-2xl md:text-4xl font-bold">
          By using the Money Move Copy Trading platform, you agree to the following terms and conditions:
        </h2>

        <p>
          Money Move shall allocate a trader to your account based on your initial deposit and risk parameters. The trader shall execute trades on your behalf according to the trader allocation plan that you choose.
        </p>

        <p>
          Money Move shall share 50% of the profits generated by the trader with you, provided that the trader has made a profit of at least 10% over your initial deposit/equity. Fintec Markets shall receive the remaining 50% to cover its trader, operational, and administration costs.
        </p>

        <p>
          Money Move shall not charge any hidden fees, such as stock trading fees, forex trading fees, copytrading fees, inactivity fees, or withdrawal fees.
        </p>

        <p>
          Money Move shall accept all brokers’ MT4/MT5 accounts, subject to the broker’s terms and conditions. You shall provide Fintec Markets with your trading account details, such as trading account number, server, and password.
        </p>

        <p>
          Money Move shall dedicate a trader to your account based on your initial deposit and risk parameters. However, you shall have the option to change the trader allocation plan or trader at any time through our platform.
        </p>

        <p>
          Money Move shall not be liable for any issues related to the execution of manual trades by the clients, such as the execution of new trades or closing a running trade that was executed by the trader. The client shall have full responsibility for executing manual trades on their own account.
        </p>

        <p>
          Money Move shall provide you with access to a dashboard that displays your trading account’s performance and the performance of the allocated trader. You shall be able to monitor your trading account and the allocated trader’s performance at any time through our platform.
        </p>

        <p>
          Money Move shall use reasonable efforts to ensure the security and confidentiality of your personal data and trading account details. However, Money Move shall not be liable for any unauthorized access to your personal data or trading account details.
        </p>

        <p>
          Money Move shall reserve the right to suspend or terminate your account at any time if you breach any of these terms and conditions or engage in any fraudulent or illegal activities.
        </p>

        <p>
          Money Move shall reserve the right to modify these terms and conditions at any time without prior notice. Your continued use of the platform after any modifications to these terms and conditions shall constitute your acceptance of the modified terms and conditions.
        </p>
      </div>

      <div className="mt-8 text-lg md:text-3xl font-bold text-[#3f5224]">
        By using the Money Move Copy Trading platform, you agree to the above terms and conditions, privacy policy, and disclaimer.
      </div>
    </div>
  );
};
